//FILE: todo_model.dart
import 'package:hive/hive.dart';

//specify name of the part file which will be generated by hive_generator
part 'trip_model.g.dart';

//Specify the HiveType with a type id between 0 and 233
//NOTE: No two TypeAdapters can have the same typeId
@HiveType(typeId: 5)
class Trip {
  //Annotate class members with HiveField with each
  //HiveField having incrementing index
  @HiveField(0)
  DateTime added;
  @HiveField(1)
  Map tripItem;

  Trip({
    required this.added,
    required this.tripItem,
  });
}
